   --- USING DATABASE EMPLOYEE ---
USE EMPLOYEE;

---CREATING SYNTAX---
CREATE TABLE EMP_1(
EMPID  CHAR(5),
MONTH  VARCHAR(10),
YEAR  INT,
DAY  INT ,
SALES  INT,
PRICE  INT);

 ---TRANSFERING OUR DATA INTO SQL SERVER BY USING BULK INSERT---
BULK INSERT EMP_1
FROM 'C:\Users\reshm\Desktop\EMP_1.csv'
WITH (FORMAT = 'CSV',
      FIRSTROW = 2,
	  FIELDTERMINATOR = ',',
	  ROWTERMINATOR = '\n');

---DATA HAS BEEN TAKEN IN 2020-2021---


---GIVE ME THE EMPID WITH MAXIMUM SALES---
 SELECT * FROM EMP_1
 WHERE SALES>20; 

 ---GIVE ME THE EMPID WHO HAVE NOT DONE ANY SALES---
 SELECT *FROM EMP_1
 WHERE SALES = 0;

 ---GIVE ME EMPID WHO HAVE DONE MORE THAN OR EQUAL TO 3 SALES---
 SELECT *FROM EMP_1
 WHERE SALES >= 3;

 ---GIVE ME THE EMPID WHO HAVE DONE 2 SALES IN YEAR 2020---
 SELECT *FROM EMP_1
 WHERE YEAR = 2020 AND SALES = 2;

 ---GIVE ME EMPID WHO HAVE NOT DONE SALES IN LAST 5 MONTHS---
 SELECT *FROM EMP_1
 WHERE MONTH BETWEEN 'AUGUST' AND 'DECEMBER';

---GIVE ME EMPID WHO HAVE NOT DONE ANY SALES IN YEAR 2021 MONTH FEB---
SELECT * FROM EMP_1
WHERE SALES = 0 AND YEAR=2021 AND MONTH >'FEB';

 


 
 


